via_json_path: 'guitar_neck_detection/data/guitar_annotations.json'
images_dir: 'guitar_neck_detection/data/resized_training_images/'
weights_path: 'guitar_neck_detection/weights/'
model_name: 'ssd_model_8_images.pth'

num_classes: 5
image_size: 512
learning_rate: .001
momentum: .9
weight_decay: .0005

